### ISSUE TITLE
why there isn't some documentation

### ISSUE THREAD

**Issue by cppdev-123** [axboe/liburing#1]
why the man pages doesn't contain any documentation about this library
and is this faster than epoll and if yes then by any factor ?

**Comment by axboe** [comment]
Because no one has written them yet? Do you want to help write them?

You might want to look into how you communicate, you come across as very demanding. You know how open source works - by people spending their time working on something they want to work on? They don't owe you anything, in fact you should be thankful for them donating their time and resources.

epoll vs io_uring, someone did this last week: https://twitter.com/CondyChen/status/1170567616525557760

**Comment by cppdev-123** [comment]
I mean is this already exists in linux or I have to do somethings to make it work
I use the man pages to explore the linux api and while searching for equivalent to iocp on windows I came to this 
sorry I am not so expert in linux , I was a windows only programmer but I'm going to program for linux because server is running linux

**Comment by codebrainz** [comment]
Tone of the OP aside, this probably shouldn't be closed since it's totally valid.
