### ISSUE TITLE
which Linux kernel version stably supports the io_uring feature?

### ISSUE THREAD

**Issue by yarthur1** [axboe/liburing#1173]
If I want to use io_uring in product environment, what linux kernel version is need? 
I would like to know which Linux kernel version stably supports the io_uring feature?

**Comment by yarthur1** [comment]
> Anything 6.x related should be fine. For mainline versions, obviously go with the 6.x variants from the stable tree, and for distros, if they keep up with stable fixes as well, everything should be fine.

thanks，I also want to know if the Linux 5.x versions reliably support io_uring?

**Comment by axboe** [comment]
5.x is a broad spectrum - in terms of stable kernels, there's 5.4, 5.10, and 5.15. 5.4 is ancient and doesn't support many of the new features, obviously. 5.10 and 5.15 are identical in terms of io_uring support.

But any 5.x kernel is going to lack a lot of the niceties and performance improvements of the 6.x kernels, which is why I said that the recommendation is to use a 6.x based kernel.

**Comment by yarthur1** [comment]
> 5.x is a broad spectrum - in terms of stable kernels, there's 5.4, 5.10, and 5.15. 5.4 is ancient and doesn't support many of the new features, obviously. 5.10 and 5.15 are identical in terms of io_uring support.
> 
> But any 5.x kernel is going to lack a lot of the niceties and performance improvements of the 6.x kernels, which is why I said that the recommendation is to use a 6.x based kernel.

Thanks a lot! I got it.
