### ISSUE TITLE
SYSCHK(syscall(__NR_io_uring_setup, 10, &params)): Invalid argument

### ISSUE THREAD

**Issue by scl2020** [axboe/liburing#1194]
May I ask how to solve this error?

**Comment by ammarfaizi2** [comment]
Oh, please, do us a favor and provide better details next time. If you had bothered to share enough specifics (like the parameters you passed in), people could have easily pointed out the mistake. EINVAL means you passed invalid parameters.

See `man 2 io_uring_setup`:

```
       EINVAL The resv array contains non-zero data, p.flags contains an
              unsupported flag, entries is out of bounds,
              IORING_SETUP_SQ_AFF was specified, but IORING_SETUP_SQPOLL
              was not, or IORING_SETUP_CQSIZE was specified, but
              io_uring_params.cq_entries was invalid.
              IORING_SETUP_REGISTERED_FD_ONLY was specified, but
              IORING_SETUP_NO_MMAP was not.
```

You probably hit one of those conditions.

**Comment by isilence** [comment]
Completely agree with @ammarfaizi2, nobody would be able to help you without any explanation and details, and I would say people and not too eager looking at such issues.

In your case it return -EINVAL because because `IORING_SETUP_DEFER_TASKRUN` requires `IORING_SETUP_SINGLE_ISSUER`. It could also be that you have an old kernel not supporting one of the flags.
