### ISSUE TITLE
IOSQE_IO_LINK and determining if a link is broken

### ISSUE THREAD

**Issue by withoutboats** [axboe/liburing#148]
thI'd like to make a generic API on top of IOSQE_IO_LINK to make it easy for users to sequence multiple events using IOSQE_IO_LINK. This API would want to only actually inform the user once the entire sequence has concluded. However, would I need to be able to determine whether the chain has completed without knowing what the event actually was.

Initially, I thought that I would track a decrementing counter in the completion object stored in user_data; once the counter reaches 0, the chain has concluded and my library should notify the user code that the chain is finished. The problem arises with handling broken chains. At first, it seemed trivial: check if the result is an error. However, io_uring considers any unexpected result an error, and breaks the chain. This is great functionality, but without storing space for an array of expected results for the entire chain, I can't know if the result is unexpected or not.

Would it seem appropriate to store in the CQE flags a bit which reports whether it is the end of an IOSQE_IO_LINK? Ideally, this bit would be set when it is *not* the end, and subsequent events in the link should be suspected? Then my completion processing code could simply drop completions that have this bit set.

**Comment by isilence** [comment]
When io_uring breaks a link, it generates a CQE with -ECANCELED for every left request. So there is exactly 1 CQE for each submitted SQE, hence the counting should work. If you need to pinpoint the failed request, try to find the one before series of -ECANCELED. This would need more complex logic if you use timeouts/cancel. Does this help?

Also, how about a kernel feature that generates only single CQE per link? It'd produce a CQE for the last request of a link if everything is right, and for the failed one otherwise. That was discussed many times, and I even had half-prepared v2, but stuck plumbing other stuff.

**Comment by isilence** [comment]
The issue got stalled without an answer from the author, I believe can be closed.
Ultimately, the userspace has all way to determine it.
