### ISSUE TITLE
Question: When does iov_base have to be posix_memalign'ed?

### ISSUE THREAD

**Issue by Xinkai** [axboe/liburing#16]
Hi,

I looked through the files under `test` and `examples`, and found some `iov_base` are allocated by `posix_memalign` and others by `malloc` or even `char*` literals.

I then did some experiments. It seemed to be that liburing does not care about memory alignment. Is this true? Thanks in advance.

https://github.com/axboe/liburing/blob/1ed37c52144de555e761500084dbffe24fede1c9/test/500f9fbadef8-test.c#L27
https://github.com/axboe/liburing/blob/556960942eaa69fd53544932f00db3fa9f196e00/test/stdout.c#L20

**Comment by axboe** [comment]
This really has nothing to do with io_uring, it only depends on if you're going to use O_DIRECT or not. If you use O_DIRECT, the kernel has alignment constraints. This is due to not copying the data, and hence the device has to DMA directly to/from the buffer .For buffered IO, it doesn't matter, as the data is copied.

**Comment by Xinkai** [comment]
Thanks for the explanation.
