### ISSUE TITLE
SSL / kTLS support?

### ISSUE THREAD

**Issue by giampaolo** [axboe/liburing#164]
Hello Jens. First of all, thank you for the great work you're doing. 
I'm currently writing a Python wrapper for `io_uring` (the plan is to integrate it into [pyftpdlib](https://github.com/giampaolo/pyftpdlib)). One thing that is crucial is being able to send files over SSL. Despite I've never experimented with it, I bumped into [kTLS](https://www.kernel.org/doc/html/latest/networking/tls.html). Can kTLS and `io_uring` be mixed together? If not, are there ways to use `io_uring` + SSL and at the same time avoid using user-space buffers (`sendfile` / `splice`)?

Sorry in advance if this has already been asked (Google didn't help).

**Comment by axboe** [comment]
It should just work with the equivalent send/sendmsg/recv/recvmsg op codes, setup will be the same. The only caveat is that control messages are currently disabled with io_uring, so that currently won't work through io_uring, but could be done on the side if you wish.

Slightly longer term, the plan is to enable control messages as well, so that that part will work too.

**Comment by giampaolo** [comment]
Thank you.

**Comment by YoSTEALTH** [comment]
@giampaolo Its also better to have a wrapper around Liburing, which is already been written if you want to try it out https://github.com/yostealth/liburing

**Comment by isilence** [comment]
The cmsg's are now supported, (iirc, since 5.12?). I think can be closed
