### ISSUE TITLE
Requesting reads larger than file size can fail

### ISSUE THREAD

**Issue by zbjornson** [axboe/liburing#175]
In Linux 5.4, running `./examples/io_uring-test ./LICENSE` prints `ret=0, wanted 4096`. I'd expect that to print `ret=1050, wanted 4096`. (The file is 1050 bytes.) I haven't tried other kernel versions. Is this expected?

Cross-posted from https://github.com/libuv/libuv/pull/2322#issuecomment-673859817.

(This might be a dupe of #135.)

**Comment by axboe** [comment]
Haven't run this on 5.4, but on the current kernel, if you actually look at completions you get:

```
ret=0, wanted 4096
ret=0, wanted 4096
ret=0, wanted 4096
ret=1050, wanted 4096
```

It's just that the first issued IO will get completed last as it went out-of-line, while the other ones are ended immediately as they are after EOF.

**Comment by axboe** [comment]
I'll try 5.4-stable, what kernel specifically are you running?

**Comment by axboe** [comment]
Same behaviour on 5.4.58:

```
ret=0, wanted 4096
ret=0, wanted 4096
ret=0, wanted 4096
ret=1050, wanted 4096
```

which I was expecting, as this kind of direct -> buffered retry happens below io_uring.

**Comment by zbjornson** [comment]
Arg, you're right, thanks for responding so quickly. Something else is going on then in my libuv PR with sporadic EFAULTs. Will dig some more before possibly bugging you for tips on that.

**Comment by axboe** [comment]
It this on 5.4? 5.4 doesn't have IORING_FEAT_SUBMIT_STABLE, that was introduced in 5.5. This means that iovecs need to be persistent from submit to completion, whereas on 5.5 and newer, they just have to be persistent until after they are submitted to the kernel. Just a guess on my side, since that is the usual explanation for EFAULT returns since the submission ends up looking at garbage if the lifetime of the iovecs aren't managed.

**Comment by zbjornson** [comment]
Brilliant, that was it, thanks!
