### ISSUE TITLE
Experimenting liburing with user space fuse library. Need help

### ISSUE THREAD

**Issue by v-harihar** [axboe/liburing#241]
Hi,

First of all thanks for the great utility like liburing. I am expecting this would be a great solution to solve our fuse context switch problem and provide much better performance.

I am working on our customized user space fuse library to do "read from/write to" "/dev/fuse" using liburing. With my initial experiments, I can able to successfully read/write the request from/to "/dev/fuse". But I did not observe much improvement (Maybe my implementation problem). So I am trying out with different flags like IORING_SETUP_IOPOLL and IORING_SETUP_SQPOLL. I faced issues with both the flags. 

Use of 
IORING_SETUP_IOPOLL is resulting in EFAULT (-14) and
IORING_SETUP_IOPOLL is resulting in EOPNOTSUPP (-95)

Can someone please suggest what needs to be fixed to get this working? 

Regards,
Vh

**Comment by axboe** [comment]
It'd be helpful if you could provide a test case, in general that helps save a lot of time and miscommunication. But for the -EOPNOTSUPP, you cannot use IOPOLL if the device/fs doesn't support it. Is your first one supposed to say SQPOLL?

**Comment by VHariharmath-rh** [comment]
Apologies. I do not have a specific test case for this. What I have done is I directly replaced the read and write handling with sq and cq in gluster fuse library and doing FOPs over the fuse mount. Also, I have run fio with iouring as engine over the fuse mount. 

How we are processing the entries?
We have a thread, which does reading the entries from /dev/fuse in a loop. There I replaced traditional read calls with submit_queue and completion queue.  The same thread also processes cqs of the write requests submitted to /dev/fuse as both read and write path uses the same ring. It is like in the same loop, submit the read request to the queue and wait for cq but cq may be a response for the request just submitted or the cq for write request that is submitted from other parts of the code. I also have provided protection to the ring with a mutex because both read and write paths access the same ring and sq and cqs are safely accessed in the same context. 

Here the fd associated with the ring is same for both read and wring and belongs to "/dev/fuse" device

I have not seen this sort of iouring usage in any of the resources available on the net but this is my experiment. With this experiment, I did not get any performance improvement in fact it got lowered by some numbers. So thought to go deep into fuse kernel module and try out all the async flags what liburing supports. 

So I tried with IORING_SETUP_IOPOLL and IORING_SETUP_SQPOLL flags but that doesn't seem to work in the single attempt and gave below errors.

Correcting the above  comment:

IORING_SETUP_SQPOLL is resulting in EFAULT (-14) and
IORING_SETUP_IOPOLL is resulting in EOPNOTSUPP (-95)

Yes, /dev/fuse may be not supporting IOPOLL but looking to make it work. Any pointers/flags you can help me out with so that I can work on fuse kernel module get it working.

I am happy to provide all details, time, and want this work with fuse module. My general feeling is that iouring is much of a need in fuse user/kernel space module to overcome the performance barriers we have as of now.

Regards,
Vh

**Comment by uroni** [comment]
I have an bare-bone fuse+io_uring example here: https://github.com/uroni/fuseuring
Performance in my case only approaches threading performance (libfuse) with large io-depth.
IORING_SETUP_SQPOLL didn't help significantly. Perhaps I need to test on better hardware...
