### ISSUE TITLE
the block is created by command ‘lvcreate’ on nvme device isn't supported polling？

### ISSUE THREAD

**Issue by ArthurZangCN** [axboe/liburing#263]
in my test，when i use command ‘lvcreate’ create a block on nvme device ，and open polling，the cqe->res is -95，because isn't supported the type？

**Comment by axboe** [comment]
dm devices do not support polling. Work is in progress on the dm side to support that, but that's outside the scope of liburing/io_uring as it's just missing support in that driver.

**Comment by ArthurZangCN** [comment]
> dm devices do not support polling. Work is in progress on the dm side to support that, but that's outside the scope of liburing/io_uring as it's just missing support in that driver.

thanks，is that future linux kernel will support it？

**Comment by axboe** [comment]
Again, this is outside the scope of this project, it's a bit like asking if some other software packages will ever do X or Y. The answer is probably "yes, it'll be supported at some point, since folks are working on it", but it's not something that any of the io_uring members are personally involved in. So I can only guess.
