### ISSUE TITLE
What operations are not supported by SQPOLL?

### ISSUE THREAD

**Issue by ShuochengWang** [axboe/liburing#273]
I found that only some operations support SQPOLL. Is there a specific list of operations that do not support? Are these unsupported operations likely to be supported in the future? Can these be noted in the documentation?

eg, connect / accept / openat / close do not support SQPOLL. I found that the code of accept and connect has the check of SQPOLL, and I got the result EBADF if I use close with SQPOLL

kernel version: 5.6.19

**Comment by CarterLi** [comment]
A silly question: AFAIK SQPOLL is only a option starting a kernel thread polling for incoming SQEs, to decrease the number of io_uring_enter syscalls.

So why `connect / accept / openat / close` are different from `read / write` and cannot be used with SQPOLL, though they all use SQEs for submitting?

**Comment by axboe** [comment]
It is sort of documented, in that it is stated that SQPOLL only works with registered files. For things like open/accept/etc, that makes no sense, as they create the file descriptor. So the main restriction here is that SQPOLL only worked with fixes files, since it didn't have access to the file table at all.

I say worked, as this is no longer true with 5.11-git. When 5.11 is released, SQPOLL will work with any command, as it's now implemented that SQPOLL can use (and modify) the file table.
