### ISSUE TITLE
What will happen if io_uring_enter(fd, (unsigned) -1, (unsigned) -1, 0, NULL) is called?

### ISSUE THREAD

**Issue by NobodyXu** [axboe/liburing#289]
Is it legal for `to_submit` and `min_complete` to be larger than number of submitted entries in SQ queue?

For example, if I pass `(unsigned) -1` to both of them, will the kernel keep consuming SQ entries until `(unsigned) -1` is 
completed?

If so, can I create a user thread that does something similar to `SQPOLL`?

```c
int io_uring_enter(unsigned int fd, unsigned int to_submit,       
                   unsigned int min_complete, unsigned int flags, 
                   sigset_t *sig);                                
```

**Comment by isilence** [comment]
1. `to_submit=-1`: it will limit it by a) number of filled CQEs (based on heads/tails) b) and on CQ ring size. If you try, you won't be able to synchronise it anyway.
 
2. `min_complete=-1`
```C
min_complete = min(min_complete, ctx->cq_entries);
```

After it will wait for that amount of CQEs. The caller should ensure that there are requests submitted that will fill those CQEs and so on, otherwise it will continue to wait. That without some details like IOPOLL and timeouts.

**Comment by NobodyXu** [comment]
> number of filled CQEs (based on heads/tails)

Is this a typo? I think you mean SQEs?

**Comment by isilence** [comment]
> > number of filled CQEs (based on heads/tails)
> 
> Is this a typo? I think you mean SQEs?

Yes. SQEs, SQ, etc. for 1.

**Comment by NobodyXu** [comment]
Thank you very much for clearifying this for me
