### ISSUE TITLE
register_files fails

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#375]
1. `open()` an file `fd`
2. runs `io_uring_register_files_update(...)` to register fd
3. close fd using `io_uring_prep_close`
4. repeat above process for many other files
5. after about 20+ open/register fd all of a sudden raises `OSError(9, 'Bad file descriptor')`

All the liburing register test passes, in one of my software test it fails. If I disable register, test passes.

Testing in Linux 5.13

**Comment by YoSTEALTH** [comment]
related to https://github.com/axboe/liburing/issues/377 problems

**Comment by isilence** [comment]
Let's reopen and keep separate, I'm not sure yet it's a valid program and so.
Can you provide some more details? Having a link to the test would be great.

**Comment by YoSTEALTH** [comment]
Will do if I can find a proper test case to reproduce this, for now its related to #377 (I think)

**Comment by isilence** [comment]
Depends how you create issues, but we want to have a separate issue for each problem. #377 is already problematic as it's just a pile of thoughts, not related userspace issues, backport/stable problems and so on, and it's hard to track anything particular there. #377 doesn't mention anything registered files related, neither I see such in logs.

So, I do consider it a separate issue, and if it would turn otherwise, we'd mark it dup'ed and close, as any other project would do. And it has no chances to be solved (if there is an issue in the first place), if it stays closed.

**Comment by YoSTEALTH** [comment]
I see.

I did created these tests and they are passing https://github.com/YoSTEALTH/Liburing/blob/master/test/register_file_test.py

**Comment by isilence** [comment]
> I did create these tests and they are passing https://github.com/YoSTEALTH/Liburing/blob/master/test/register_file_test.py

Ok, so... is everything works now? If not, what is the question or the problem?

**Comment by YoSTEALTH** [comment]
Yes, everything is working now. Other issue was causing this issue, since its fixed, its all good.
