### ISSUE TITLE
polling mode using liburing example

### ISSUE THREAD

**Issue by kennthhz** [axboe/liburing#385]
Is there a good example code using liburing API under polling mode?

**Comment by YoSTEALTH** [comment]
@kennthhz https://unixism.net/loti/index.html

**Comment by axboe** [comment]
For the sake of completeness, there are two kinds of polling supported by io_uring:

1) SQPOLL, enabled by setting IORING_SETUP_SQPOLL when creating the ring. This creates a thread that runs in kernel space, and the thread polls the SQ ring for new completions to submit. This eliminates the submission overhead from the application, and allows it to perform IO/syscalls without ever doing a syscall itself.

2) IOPOLL, enabled by setting IORING_SETUP_IOPOLL when creating the ring. This enables IO to files/block devices without triggering interrupts. The application, when doing a wait-for-events io_uring_enter syscall, will actively poll for completions on the target device. This reduces overhead for high IOPS applications, and reduces latency in general.

You can set both flags, and then the SQPOLL thread will also poll for completions outside of its submission duties. There _really_ isn't anything special you need to do in your application outside of setting those flags. The only slight exception is the return value of submits with SQPOLL, since it isn't reliable with kernel side submission. You need to be careful tracking pending requests with that option, as you can't rely on the return value to tell you how many _new_ SQEs got submitted. It'll always return the value you asked for.

**Comment by ciconia** [comment]
Is there any downside to using either of these flags?

**Comment by isilence** [comment]
SQPOLL required privileges before, got lifted in 5.13 or somewhere around, in much earlier versions it didn't support all operation types. Also it creates +1 thread, kind of.
IOPOLL supports only reads and writes, and a couple of opcode for updating buffers and files. And not every file fully supports IOPOLL, e.g. sockets don't.
And all typical pros and cons of polling.

**Comment by kennthhz** [comment]
I do see the submission queue polling example at https://unixism.net/loti/tutorial/sq_poll.html
But I don't see completion queue polling. Is cq polling simply a loop calling int ret = io_uring_wait_cqe(ring, &cqe)? So io_uring_wait_cqe is used in both interrupt and cq polling scenario. The difference in behavior is decided by setting IORING_SETUP_SQPOLL and/or IORING_SETUP_IOPOLL during ring setup? It is not clear from reading the above documentation on cq polling. Thanks

**Comment by YoSTEALTH** [comment]
The `for` loop after `io_uring_submit(ring);` is where you get the result from `cq`. `cqe` is submitted by `io_uring` at kernel side. You see the result in `cqe.res` e.g `fd = cqe.res` or `read_length = cqe.res`

To put it simple, don't think you should be using either `IORING_SETUP_SQPOLL` or `IORING_SETUP_IOPOLL` atm. Its for those people that have an itch to scratch to get bit more speed by spending a lot of time tweaking :D. By default io_uring is already asynchronous and io_uring already handles most of the heavy lifting for you.

**Comment by kennthhz** [comment]
Thanks @YoSTEALTH. I am in the business of database engine so I need to squeeze the last bit of juice when it comes to latency and throughput. My question above is to verify my understanding of how to code cq size in both interrupt and polling mode. My understanding is that in either mode, my cq side of the code should be the same as below's for loop. If it is interrupt mode, the io_uring_wait_cqe may block until at least one cqe is available. If it is polling mode, then io_uring_wait_cqe should be non-blocking and I need to look at cqe.res to see if poll has reaped any result. Is this understanding correct? 

    for(int i = 0; i < 2; i ++) {
        int ret = io_uring_wait_cqe(ring, &cqe);

**Comment by YoSTEALTH** [comment]
There is no `interrupt` or `non-blocking` (as far as I know). With `io_uring_wait_cqe` you are waiting for at least `1` `cq` to be ready, yes. You can use other functions like `io_uring_wait_cqe_nr(ring, cqes, 0)`, this will wait for `0`, so no waiting. `io_uring_wait_cqes` you can wait single/multiple with timeout. There are many other functions... (look in the src code)

`cqe.res` only return result or `-errno`, you would have to use it with `cqe.user_data` you set in `sqe.user_data = 1` to see what submission entry it matches. You check for `cqe.res` after entry is ready.

To check if something is ready or not there are many ways to go about it, here is an article I like that explains it well https://developpaper.com/native-linux-asynchronous-file-operation-io_uring-experience/ also look at example and test, they are good source of info

**Comment by isilence** [comment]
1. iopolling is **not** CQ polling, but rather a kind of `RWF_HIPRI`. You should see any difference in how you submit of wait for requests.
2. There is a way to check for CQEs without entering the kernel, e.g. see `io_uring_peek_cqe()`. So, in theory you can do CQ polling using it, but most probably it's a bad idea. It also won't work with iopoll.
3. If you wonder, `io_uring_wait_cqe()` and others may return back quick without entering the kernel, it would first try `io_uring_peek_cqe()` inside.

**Comment by aosterthun** [comment]
I'm not quite sure if I understood this correctly so I'm just gonna reiterate quickly:
1. io polling can be enabled setting the IORING_SETUP_IOPOLL flag in the io_uring_queue_init() or io_uring_queue_init_params() call
2. I do not need to change any other code since io polling is polling the device until the data has been read an then creates a completion queue event that is captured in user space with io_uring_wait_cqe, which is no different from working with interrupts besides that in that case the device notifies the kernel and then creates the completion queue entry.
3. Would there be any benefit to actually poll the completion queue as well ?

**Comment by isilence** [comment]
>     1. io polling can be enabled setting the IORING_SETUP_IOPOLL flag in the io_uring_queue_init() or io_uring_queue_init_params() call

Right
 
>     2. I do not need to change any other code since io polling is polling the device until the data has been read an then creates a completion queue event that is captured in user space with io_uring_wait_cqe, which is no different from working with interrupts besides that in that case the device notifies the kernel and then creates the completion queue entry.

Yes, something like that. The major difference of IOPOLL mode is that it only supports read/write operations + a couple of others like files_update. But apart from that, there are only subtle differences and liburing handles them, so just use `io_uring_wait_cqe()`, and it'll be fine.

__TL;DR;__ in IOPOLL mode most of CQEs won't arrive without entering the kernel, so this won't work (i.e. CQ polling):

```C
while(io_uring_peek_cqe(&cqe) == -EAGAIN) { ; } // repeat
handle_cqe(cqe);
```

But that's wasteful in any case and I hope nobody does that. Just use `io_uring_wait_cqe()` or some combination of peek + wait.

>     3. Would there be any benefit to actually poll the completion queue as well ?

I'd rather say no. You would need a _very_ specific case to benefit from that, because liburing already reaps CQEs it in a hybrid fashion trying to avoid entering the kernel when possible.

**Comment by aosterthun** [comment]
Proposing I would want to handle CQEs in a separate thread, how would I do that without CQ polling. When I use `io_uring_wait_cqe()` the thread would lock while waiting for a new CQE. This would result in `io_uring_queue_exit()` not beeing able to clean up the ring until that thread would be in a non locked state. Since `io_uring_wait_cqe()` would probably would be called in a loop the thread is basically permanently locked. In order to avoid that I would need to use `io_uring_peek_cqe()` to check if a CQE is available before calling `io_uring_wait_cqe()`, which is more or less the pattern that was advised against [here](https://github.com/axboe/liburing/issues/385#issuecomment-891752518).

**Comment by isilence** [comment]
apart from letting the thread know how much I/O to expect:
option 1: send a signal, it'll wake it up
option 2: issue a timeout request, it'll wake up all CQ waiters in the kernel, but don't remember whether liburing handles it well.

**Comment by kennthhz** [comment]
Just so I am clear, iopolling is about submit (client side) polling. A kernel thread that poll the sq to submit without system call. There is no such kernel side polling support for cq side. The application writer should just use io_uring_wait_cqe or its variant right? 
However, I do remember io_uring documentation when talking about iopolling, it also talks about it is faster than interrupt based signaling. But if it is a pure submission side polling, how is it related to interrupt? I would thinks interrupt is about completion signal, hence I thought polling is about cq.

**Comment by aosterthun** [comment]
As I understand it this is what happens when you execute an IO command: You prepare a submission queue entry (SQE). When submission queue polling (SQPOLL) is enabled the kernel thread will poll the submission queue for new SQEs to execute. If you don't use SQPOLL or the SQPOLL thread has gone to sleep you need to submit the SQE through `io_uring_submit()`. Now the SQE will be executed. After going through the file system layers, io_uring will ask the storage device for some pages. Without using IO polling, io_uring will rely on the storage device to send an interrupt to let io_uring know that the operation is completed and that a completion queue entry(CQE) can be generated. If IO polling is enabled io_uring will not rely on interrupts, but will poll the device until the operation is completed and creates a CQE. This should be faster since you do not need to suspend the normal execution flow to handle the storage device interrupt, or wait for the interrupt to be handled at all. So with regards to handling CQEs there isn't really a difference between using IO polling or not, since IO polling really only changes the way io_uring waits for the completion of an IO operation on the storage device level. The call to `io_uring_wait_cqe()` will be blocking in any case regardless of using IO polling or not. 

In any case, the interface of io_uring suggests to me that it is more about asynchronously submitting your IO and not about asynchronously handling completion events for IO. Which kinda makes sense since you probably need all IO for a certain task executed anyway so it's not really important to get the completion event as fast as you can, but about submitting IO operations asynchronously so that they are executed at once. And then using the `io_uring_wait_cqe()` call to more or less "join" the different IO operations back together before using it elsewhere in your application. 

I think actually polling the completion events only makes sense if you submit a lot of single read operations in parallel. Because in that case you want the asynchronicity on the submission side, but also don't want to wait on the completion side to wait for a set of IO operations to be finished but ideally want to pass the data directly to other parts of your application. I would assume with increasing size of the data to be read this becomes even more viable, since the IO operations just takes longer.

**Comment by aosterthun** [comment]
> apart from letting the thread know how much I/O to expect:
> option 1: send a signal, it'll wake it up
> option 2: issue a timeout request, it'll wake up all CQ waiters in the kernel, but don't remember whether liburing handles it well.

I don't really know what you mean by option one. Regarding option 2, I would send a timeout when I want to stop waiting for incoming CQEs, which would allow me to exit the wait loop and gracefully shut down the application. 

Taken from the [Lord of the io_uring](https://unixism.net/loti/ref-iouring/io_uring_enter.html):
> This command will register a timeout operation. The addr field must contain a pointer to a struct timespec64 structure, len must contain 1 to signify one timespec64 structure, timeout_flags may contain IORING_TIMEOUT_ABS for an absolute timeout value, or 0 for a relative timeout. off may contain a completion event count. If not set, this defaults to 1. A timeout will trigger a wakeup event on the completion ring for anyone waiting for events. A timeout condition is met when either the specified timeout expires, or the specified number of events have completed. Either condition will trigger the event. io_uring timeouts use the CLOCK_MONOTONIC clock source. The request will complete with -ETIME if the timeout got completed through expiration of the timer, or 0 if the timeout got completed through requests completing on their own. If the timeout was cancelled before it expired, the request will complete with -ECANCELED. Available since 5.4.

**Comment by isilence** [comment]
> > apart from letting the thread know how much I/O to expect:
> > option 1: send a signal, it'll wake it up
> > option 2: issue a timeout request, it'll wake up all CQ waiters in the kernel, but don't remember whether liburing handles it well.
> 
> I don't really know what you mean by option one.

sigqueue() or others
https://www.man7.org/linux/man-pages/man3/sigqueue.3.html

> Regarding option 2, I would send a timeout when I want to stop waiting for incoming CQEs, which would allow me to exit the wait loop and gracefully shut down the application.

I'm not sure whether the advice helped, or you did use it even before that, but let us know if there are still concerns.

> 
> Taken from the [Lord of the io_uring](https://unixism.net/loti/ref-iouring/io_uring_enter.html):

To keep references correct, all that below is actually taken from man,
https://github.com/axboe/liburing/blob/master/man/io_uring_enter.2#L324

> > This command will register a timeout operation. The addr field must contain a pointer to a struct timespec64 structure, len must contain 1 to signify one timespec64 structure, timeout_flags may contain IORING_TIMEOUT_ABS for an absolute timeout value, or 0 for a relative timeout. off may contain a completion event count. If not set, this defaults to 1. A timeout will trigger a wakeup event on the completion ring for anyone waiting for events. A timeout condition is met when either the specified timeout expires, or the specified number of events have completed. Either condition will trigger the event. io_uring timeouts use the CLOCK_MONOTONIC clock source. The request will complete with -ETIME if the timeout got completed through expiration of the timer, or 0 if the timeout got completed through requests completing on their own. If the timeout was cancelled before it expired, the request will complete with -ECANCELED. Available since 5.4.

**Comment by aosterthun** [comment]
I will test the timeout version and let you now if I got it to work.

**Comment by isilence** [comment]
> As I understand it this is what happens when you execute an IO command: You prepare a submission queue entry (SQE). When submission queue polling (SQPOLL) is enabled the kernel thread will poll the submission queue for new SQEs to execute. If you don't use SQPOLL or the SQPOLL thread has gone to sleep you need to submit the SQE through `io_uring_submit()`.

Or more precisely, always call `io_uring_submit()`, and it'll decide whether it needs to switch to the kernel. There may be other reasons it may enter the kernel, so don't skip it.

> Now the SQE will be executed. After going through the file system layers, io_uring will ask the storage device for some pages. Without using IO polling, io_uring will rely on the storage device to send an interrupt to let io_uring know that the operation is completed and that a completion queue entry(CQE) can be generated. If IO polling is enabled io_uring will not rely on interrupts, but will poll the device until the operation is completed and creates a CQE.

note: will be polled in `io_uring_wait_cqe()`.

> This should be faster since you do not need to suspend the normal execution flow to handle the storage device interrupt, or wait for the interrupt to be handled at all. 

And also because of iopoll specific optimisations on the io_uring side.

> So with regards to handling CQEs there isn't really a difference between using IO polling or not, since IO polling really only changes the way io_uring waits for the completion of an IO operation on the storage device level. The call to `io_uring_wait_cqe()` will be blocking in any case regardless of using IO polling or not.

Right

**Comment by aosterthun** [comment]
> > > apart from letting the thread know how much I/O to expect:
> > > option 1: send a signal, it'll wake it up
> > > option 2: issue a timeout request, it'll wake up all CQ waiters in the kernel, but don't remember whether liburing handles it well.
> > 
> > 
> > I don't really know what you mean by option one.
> 
> sigqueue() or others
> https://www.man7.org/linux/man-pages/man3/sigqueue.3.html
> 
> > Regarding option 2, I would send a timeout when I want to stop waiting for incoming CQEs, which would allow me to exit the wait loop and gracefully shut down the application.
> 
> I'm not sure whether the advice helped, or you did use it even before that, but let us know if there are still concerns.
> 
> > Taken from the [Lord of the io_uring](https://unixism.net/loti/ref-iouring/io_uring_enter.html):
> 
> To keep references correct, all that below is actually taken from man,
> https://github.com/axboe/liburing/blob/master/man/io_uring_enter.2#L324
> 
> > > This command will register a timeout operation. The addr field must contain a pointer to a struct timespec64 structure, len must contain 1 to signify one timespec64 structure, timeout_flags may contain IORING_TIMEOUT_ABS for an absolute timeout value, or 0 for a relative timeout. off may contain a completion event count. If not set, this defaults to 1. A timeout will trigger a wakeup event on the completion ring for anyone waiting for events. A timeout condition is met when either the specified timeout expires, or the specified number of events have completed. Either condition will trigger the event. io_uring timeouts use the CLOCK_MONOTONIC clock source. The request will complete with -ETIME if the timeout got completed through expiration of the timer, or 0 if the timeout got completed through requests completing on their own. If the timeout was cancelled before it expired, the request will complete with -ECANCELED. Available since 5.4.

Option 2 works like a charm. You obviously need to stop the loop in which you call `io_uring_wait_cqe()` first, before you send the timeout because otherwise you are just waiting again, but in general this seems to be a good solution for running CQE handling in a separate thread.

**Comment by kennthhz** [comment]
@aosterthun do you have sample code for using IORING_OP_TIMEOUT? Not sure I understand "You obviously need to stop the loop in which you call io_uring_wait_cqe() first, before you send the timeout because otherwise you are just waiting again"

**Comment by eecheng87** [comment]
I'm not quite sure if I understood this correctly. If ` IORING_SETUP_SQPOLL ` was set, it will create a kernel thread
which check if there're available operation on submission queue. If true, the task on sq will automatically be done without
calling `io_uring_submit`.

If the above is true, why do [lord of io_uring example: sq_poll.c](https://github.com/shuveb/loti-examples/blob/master/sq_poll.c#L67) still call `io_submit`?

Thanks in advance.

**Comment by aosterthun** [comment]
> @aosterthun do you have sample code for using IORING_OP_TIMEOUT? Not sure I understand "You obviously need to stop the loop in which you call io_uring_wait_cqe() first, before you send the timeout because otherwise you are just waiting again"


```c++
std::atomic<bool> keep_waiting_for_cqes;

void completion_handler(){
   while(keep_waiting_for_cqes){
      ret = io_uring_wait_cqe();
   }
}

void handle_shutdown(int signal){
   keep_waiting_for_cqes = false;
   io_uring_sqe* sqe;
   __kernel_timespec ts = {.tv_sec = 0, .tv_nsec = 1};
   sqe                  = io_uring_get_sqe();
   io_uring_prep_timeout(sqe, &ts, 1, 0);
   io_uring_submit(&ring);
}

void main(){
   signal(SIGINT, &handle_shutdown);
   std::thread completion_handler_thread(&completion_handler);
   completion_handler_thread.join();
}
```
This is a rough reproduction of my approach. I sadly did not have much time testing this approach, but I encountered the problem, that the completions usually take to long which results in running out of SQEs (queue depth limit). I tested this in a VM so I do not know if this is a problem with the approach or just the virtual storage device being slow.

**Comment by YoSTEALTH** [comment]
@aosterthun not really sure what you are trying to do, maybe you want `io_uring_prep_timeout(sqe, &ts, 0, 0);` `count=1  // IORING_TIMEOUT_ABS`,  `count=0  // Relative Timeout` (as far as i understood it)

**Comment by osevan** [comment]
Any patches available for polling mode for mariadb server?

https://github.com/MariaDB/server/blob/374783c3d9a87170b313a05240dadaa813ec6034/tpool/aio_liburing.cc#L21

**Comment by axboe** [comment]
If it's using O_DIRECT for IO, then all you really need to do to try polling would be:

1) Initialize the queue with IORING_SETUP_IOPOLL set in the in flags
2) If on NVMe storage, ensure you have nvme.poll_queues set in your module or kernel parameters

It'll work without number 2 above, but it won't be polled IO. Verify with checking dmesg when nvme has loaded, it should have a non-zero value for poll queues ala:

```
nvme nvme8: 119/0/16 default/read/poll queues
```

**Comment by osevan** [comment]
Hey axboe,

thx for reply, but im bit mighty in c language functuions writing. 

I can understand,  gut not write c code. 


Could you edit above code for full working liburing poll mode?


Thanks and

Best regards

**Comment by axboe** [comment]
You change this line:

```
if (io_uring_queue_init(max_aio, &uring_, 0) != 0)
```

to

```
if (io_uring_queue_init(max_aio, &uring_, IORING_SETUP_IOPOLL) != 0)
```

and that should work, but it may be more involved in that depending on how the event loop is run. For example, if it uses peek for events, then it may need more changes. Or if it mixes non-read/write requests on the same ring, then you'd need a separate ring for just the read/write polled IO. I don't have time to do this or work on it, unfortunately.
