### ISSUE TITLE
Non-blocking Write?

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#451]
It would be cool if `io_uring` could do non-blocking `write`.

I was thinking of writing an(confusing) explanation on here as to how it should all work but thankfully someone has already done all the work it seems, couple of paper I found online:

https://users.cs.fiu.edu/~raju/WWW/publications/fast2015/paper.pdf
https://pdfs.semanticscholar.org/e1bc/b0be9327b6e0422ca9796d55f3481af80b39.pdf

**Comment by YoSTEALTH** [comment]
Agree, with the double/bounce buffering. Zero copy the better. Even so, if that method can show such performance improvement, `io_uring` implementation would be even more significant!

It seems like the case of... just have to implement something to see how it performs and what are all the gotchas along the way?

Not sure what you mean by "copy the data" as in copy the data to disk/drive?

One of the gotcha could be; If you write directly from the buffer (in memory) to disk (since its non-blocking), another task could write to the same buffer. So the buffer would have to be locked till the write is done. Also return `EAGAIN` if tried to write to the same buffer.

**Comment by axboe** [comment]
It's not zero copy, a buffered write is one copy. The problem with the proposed solution in the paper is that it copies it twice - once for a kernel buffer, and then again to hit the page cache.

> Not sure what you mean by "copy the data" as in copy the data to disk/drive?

Since it's buffered IO, it's all synchronized by the page cache. Hence you need to copy that temporary buffer into the page cache. You could in theory DMA directly to the drive, but then you'd run into all sorts of concurrency issues if someone else writes to the same spot at that time, or while that IO is still pending. That's why you serialize through the page cache.
