### ISSUE TITLE
Can't test io_uring in GitHub CI/CD workflow

### ISSUE THREAD

**Issue by ciconia** [axboe/liburing#498]
I'm having trouble testing [Polyphony](https://github.com/digital-fabric/polyphony) with the io_uring backend on GitHub actions. Calling `io_uring_queue_init` returns `-ENOMEM` (details [here](https://github.com/digital-fabric/polyphony/runs/4557845403?check_suite_focus=true#step:7:4)). The reported kernel version is:

```
$ uname -a
Linux fv-az193-334 5.11.0-1022-azure #23~20.04.1-Ubuntu SMP Fri Nov 19 10:20:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

A user also [reported problems](https://github.com/digital-fabric/polyphony/issues/66) using Polyphony in a Docker container a while ago, where calling `io_uring_get_sqe` would cause a segfault at `0x0000000000000000`. The two problems might be related?

What are the implications of using io_uring in a container situation?

Thanks!

**Comment by axboe** [comment]
This is most likely due to trying to create a ring with an amount of entries large enough to exceed the rlimit memlock setting. Either that, or potentially memory fragmentation.

For the sqe == NULL issue, that can only happen if the SQ ring is empty. You have allocated all the SQEs that you can, and you need to submit pending entries to the kernel to get consumed.

> What are the implications of using io_uring in a container situation?

io_uring doesn't really care about whether it runs in a container or not, shouldn't have any special implications there.
