### ISSUE TITLE
A question about x86_64 syscall implementation

### ISSUE THREAD

**Issue by JackyYin** [axboe/liburing#530]
Greeting, recently I am trying to replace some of `epoll` implementation with `io_uring` for better performance, but I have some questions about the implementation details of this library.

Firstly, I saw `__do_sycall1  ~ __do_syscall6` in `src/arch/x86/syscall.h`.

I can understand that this assembly code is another way of invoking syscall in `x86_64` architecture, but what is the difference between this and a direct syscall like `io_uring_register(A,B,C,D)` ?

Is that because of the use of registers to achieve a better performance? (But I though this is the default behavior of `x86_64`, when the number of parameters is less than or equal to 6.)
```c
#define __do_syscall1(NUM, ARG1) ({		\
	intptr_t rax;				\
						\
	__asm__ volatile(			\
		"syscall"			\
		: "=a"(rax)	/* %rax */	\
		: "a"((NUM)),	/* %rax */	\
		  "D"((ARG1))	/* %rdi */	\
		: "rcx", "r11", "memory"	\
	);					\
	rax;					\
})
```

**Comment by ammarfaizi2** [comment]
## Background Story

This architecture-specific code originally addressed the nolibc build and was only used for nolibc build. See the full story here:
https://github.com/axboe/liburing/issues/443

Since this patchset https://lore.kernel.org/io-uring/20220211155753.143698-1-ammarfaizi2@gnuweeb.org/T/ we always these inline assembly macros for nolibc and libc build. Currently, the implementation is only available for the x86-64 arch. For other architectures, we use the `syscall(2)` libc wrapper.

## Comparing libc syscall(2) with inline Assembly x86-64

Let's take one function and compare the Assembly. In this example, we take `__io_uring_sqring_wait`.

### With libc syscall(2)
```asm
0000000000003370 <__io_uring_sqring_wait>:
    3370:       f3 0f 1e fa             endbr64 
    3374:       48 83 ec 10             sub    $0x10,%rsp
    3378:       8b b7 c4 00 00 00       mov    0xc4(%rdi),%esi
    337e:       31 c9                   xor    %ecx,%ecx
    3380:       31 d2                   xor    %edx,%edx
    3382:       6a 08                   push   $0x8
    3384:       41 b8 04 00 00 00       mov    $0x4,%r8d
    338a:       45 31 c9                xor    %r9d,%r9d
    338d:       bf aa 01 00 00          mov    $0x1aa,%edi
    3392:       31 c0                   xor    %eax,%eax
    3394:       e8 b7 df ff ff          call   1350 <syscall@plt>
    3399:       5a                      pop    %rdx
    339a:       59                      pop    %rcx
    339b:       41 89 c0                mov    %eax,%r8d
    339e:       85 c0                   test   %eax,%eax
    33a0:       79 0b                   jns    33ad <__io_uring_sqring_wait+0x3d>
    33a2:       e8 c9 de ff ff          call   1270 <__errno_location@plt>
    33a7:       44 8b 00                mov    (%rax),%r8d
    33aa:       41 f7 d8                neg    %r8d
    33ad:       44 89 c0                mov    %r8d,%eax
    33b0:       48 83 c4 08             add    $0x8,%rsp
    33b4:       c3                      ret 
```

### With inline assembly
```asm
0000000000003370 <__io_uring_sqring_wait>:
    3370:   f3 0f 1e fa             endbr64 
    3374:   31 d2                   xor    %edx,%edx
    3376:   8b bf c4 00 00 00       mov    0xc4(%rdi),%edi
    337c:   45 31 c0                xor    %r8d,%r8d
    337f:   b8 aa 01 00 00          mov    $0x1aa,%eax
    3384:   41 ba 04 00 00 00       mov    $0x4,%r10d
    338a:   41 b9 08 00 00 00       mov    $0x8,%r9d
    3390:   89 d6                   mov    %edx,%esi
    3392:   0f 05                   syscall 
    3394:   c3                      ret
```

Both provide the same functionality, but the inline Assembly is much more compact and simpler. Several benefits of using inline Assembly:

1) Reducing function calls. By using libc `syscall(2)`, we have two extra function calls, the `syscall(2)` wrapper itself and `__errno_location` (it comes from the `errno` variable, it's actually a macro that expands to a function call). By using inline Assembly, these two function calls are completely removed.

2) Reducing branches. Using libc `syscall(2)` needs extra branches to check for errors. If `syscall(2)` returns -1, we read the `errno` variable and negate it to make the return value of liburing's functions negative. By using inline Assembly, this branch and `errno` variable negation are completely removed.

3) Smaller binary size. Point (1) and (2) will also reduce the data movement, hence smaller Assembly code, smaller binary size.

4) Reduce `%rip` round trip to libc.so. Call to a libc function will make the `%rip` jump to libc.so memory area. This can have extra overhead and extra icache misses in some scenarios. If we inline the syscall instruction, this overhead can be removed.

5) Allow the compiler to reuse call-clobbered registers. By the rule of System V ABI x86-64, a function call clobbers `%rax`, `%rdi`, `%rsi`, `%rdx`, `%rcx`, `%r8`, `%r9`, `%r10` and `%r11`. On Linux, syscall only clobbers `%rax`, `%rcx` and `%r11`. But since libc `syscall(2)` wrapper is a function call, the compiler will always miss the opportunity to reuse those clobbered registers. That means it has to preserve the life values on the stack if they happen to be in the clobbered registers (that's also extra memory access). By using inline Assembly, the compiler is allowed to reuse the old value of all registers, except `%rax`, `%rcx` and `%r11`.

**Comment by JackyYin** [comment]
@ammarfaizi2 Thanks a bunch, this should be the most inspiring and detailed answer I have ever seen, really appreciate your hard work and your answer. 👍 👍 👍
