### ISSUE TITLE
Need for `user_data` field in `io_uring_prep_*` functions

### ISSUE THREAD

**Issue by lamarrr** [axboe/liburing#548]
I'm able to submit multiple requests and have multiple requests in flight.
CQEs are reaped without a specific ordering. I need to identify which SQE an equivalent CQE corresponds to. But this is not possible as all `io_uring_prep_*` functions set the `user_data` field to null (0). the `user_data` field is needed for this CQE to SQE matching (as described here: https://man.archlinux.org/man/io_uring.7.en)

**Comment by alviroiskandar** [comment]
On Fri, Mar 18, 2022 at 5:41 PM Basit Ayantunde wrote:
> I'm able to submit multiple requests and have multiple requests in
> flight. CQEs are reaped without a specific ordering. I need to identify
> which SQE an equivalent CQE corresponds to. But this is not possible as
> all io_uring_prep_* functions set the user_data field to null (0). the
> user_data field is needed for this CQE to SQE matching (as described
> here: https://man.archlinux.org/man/io_uring.7.en)

If you need user_data, use io_uring_sqe_set_data() or set it directly
via sqe->user_data. For older liburing versions, the user_data should
be set after prep.

Since commit 8ecd3fd959634d ("Don't clear sqe->user_data as part of
command prep"), the io_uring_prep_* functions no longer set the
user_data to NULL.

-- Viro

**Comment by axboe** [comment]
As mentioned, newer liburing doesn't do that anymore. For older ones, you just have to ensure you set it post calling prep. If for some reason you cannot do that, then you'd need to save and restore...

**Comment by alviroiskandar** [comment]
On Fri, Mar 18, 2022 at 5:41 PM Basit Ayantunde wrote:
> I'm able to submit multiple requests and have multiple requests in
> flight. CQEs are reaped without a specific ordering. I need to identify
> which SQE an equivalent CQE corresponds to. But this is not possible as
> all io_uring_prep_* functions set the user_data field to null (0). the
> user_data field is needed for this CQE to SQE matching (as described
> here: https://man.archlinux.org/man/io_uring.7.en)

If you need user_data, use io_uring_sqe_set_data() or set it directly
via sqe->user_data. For older liburing versions, the user_data should
be set after prep.

Since commit 8ecd3fd959634d ("Don't clear sqe->user_data as part of
command prep"), the io_uring_prep_* functions no longer set the
user_data to NULL.

-- Viro

**Comment by alviroiskandar** [comment]
On Fri, Mar 18, 2022 at 5:41 PM Basit Ayantunde
***@***.***> wrote:
> I'm able to submit multiple requests and have multiple requests in
> flight. CQEs are reaped without a specific ordering. I need to identify
> which SQE an equivalent CQE corresponds to. But this is not possible as
> all io_uring_prep_* functions set the user_data field to null (0). the
> user_data field is needed for this CQE to SQE matching (as described
> here: https://man.archlinux.org/man/io_uring.7.en)

If you need user_data, use io_uring_sqe_set_data() or set it directly
via sqe->user_data.

Also, since commit 8ecd3fd959634d ("Don't clear sqe->user_data as part
of command prep"), the io_uring_prep_* functions no longer set the
user_data to NULL.

-- Viro

**Comment by alviroiskandar** [comment]
I'm a bit shocked seeing those two duplicate replies on behalf of my
account. I didn't do that, nor accidentally did. What a silly thing.

I think it's a bug in the GitHub email reply system. Seeing the date
and the time they are posted, I can confirm that there is no
activity in my email account at that time.

Ignore.
