### ISSUE TITLE
After socket being closed io_uring does not cancel operations submitted to the socket.

### ISSUE THREAD

**Issue by tofes** [axboe/liburing#568]
Following up on [Question 528](https://github.com/axboe/liburing/issues/528) and discussion on [Ask 401](https://github.com/chriskohlhoff/asio/issues/401),  io_uring doesn't cancel associated operations after a corresponding descriptor has been closed. For example, in my test I saw once I closed a blocking socket, the pending submitted read requests were not cancelled and write requests were completed instead of being cancelled. This behavior is different from existing system.

Is there a good way to ensure all pending operations on a socket are cancelled once the socket is closed? I do not mean to exit io_uring since there may be other socket connections that use the same io_uring.

**Comment by axboe** [comment]
This branch has some untested support for this:

https://git.kernel.dk/cgit/linux-block/log/?h=for-5.19/io_uring-cancel_fd

Basically it adds the following support to ```IORING_OP_ASYNC_CANCEL```:

- You can set ```IORING_ASYNC_CANCEL_ALL``` in ```sqe->cancel_flags```, in which case the request will cancel all requests that match the criteria
- You can set ```IORING_ASYNC_CANCEL_FD``` in ```sqe->cancel_flags```. If this is set, rather than cancel requests that match the ```user_data``` of ```sqe->addr```, we match the file assigned from ```sqe->fd```.

For your use case, you'd then want to assign ```fd``` to the socket fd and set both of these flags in the cancelation request. I'll write up a test case for this since it is as-of yet untested, but that should get the idea across.

Note that if ```IORING_ASYNC_CANCEL_ALL``` is set, then the completion result is a positive value for number of requests canceled, and ```-ENOENT``` if none were found.

**Comment by Cloudef** [comment]
@axboe Sorry for pinging you directly. I'd like to know official answer to above to make my decision how to handle this scenario downstream.

**Comment by isilence** [comment]
That's still the case, and IMHO it should be left this way. At least I wouldn't want to do dirty tricks epoll does in similar situations. The options are either to explicitly cancel requests for the socket as Jens described above, or shutdown(2) the socket, which would cancel inflight requests.

**Comment by Cloudef** [comment]
Thank you for your response. I'll document this behavior and accept it as answer.
