### ISSUE TITLE
Feature request: support IORING_OP_{SEND,RECV}_FIXED for consistance

### ISSUE THREAD

**Issue by CarterLi** [axboe/liburing#57]
We support IORING_OP_{READ,WRITE}_FIXED but doesn't support IORING_OP_{SEND,RECV}_FIXED.

**Comment by isilence** [comment]
Was mentioned multiple times in different threads, it's not implemented because it doesn't help performance for normal / non-zerocopy send/recv. The question is whether there is a good use case you have for having it?

In terms of API, it doesn't need separate opcodes, `OP_{SEND,RECV}[MSG]` and can just implement `IORING_RECVSEND_FIXED_BUF`.
