### ISSUE TITLE
Can io_uring support the feature sharing the sq_thread in one cpu?

### ISSUE THREAD

**Issue by korant96** [axboe/liburing#713]
Hi Pavel Begunkov:     
I noticed there used to be the issue taking about this feature. [IORING_SETUP_SQPOLL_PERCPU status?](https://github.com/axboe/liburing/issues/324)     
But I am a litte confuesd, I want to friendly ask does io_uirng created by different process share the sq_thread in one cpu?    

Please forgive me if the question is stupid～     

@isilence

**Comment by isilence** [comment]
> I noticed there used to be the issue taking about this feature. [IORING_SETUP_SQPOLL_PERCPU status?](https://github.com/axboe/liburing/issues/324) But I am a litte confuesd, I want to friendly ask does io_uirng created by different process share the sq_thread in one cpu?

In short, no, it doesn't.

Sharing of sqpoll was only allowed by using ATTACH_WQ and it has actually become more restrictive since around 5.10 when unless the processes creating io_uring sqpoll instances are in the same task group, i.e. are threads of the same process, it'll create a new sqpoll task for each of them, see `IORING_FEAT_NATIVE_WORKERS`. In retrospective, it was the right decision, saves a lot of trouble and dozens of potential security problems,

And just a quick note that that SQPOLL is not an automatic way to get more performance, normal rings work fine and may easily outperform sqpoll depending on use case and especially if SQPOLL is not fine tuned by the app.

**Comment by korant96** [comment]
Thanks so much for your kind reply.
So It menas the flag "IORING_SETUP_ATTACH_WQ" can only share the sqthread by the ctx created the one process since v5.10.
> _SQPOLL tasks already can be shared, IORING_SETUP_ATTACH_WQ + setting struct io_uring_params::wq_fd to another io_uring fd with which you want to share backends._

Above commet is quoted from you in issue#324. And it is also for the same thread group, right?

**Comment by isilence** [comment]
> Thanks so much for your kind reply. So It menas the flag "IORING_SETUP_ATTACH_WQ" can only share the sqthread by the ctx created the one process since v5.10.

It's allowed and would work, but internally it'll create two SQPOLL kernel tasks and effectively doesn't differ from not sharing SQPOLL at all.

> > _SQPOLL tasks already can be shared, IORING_SETUP_ATTACH_WQ + setting struct io_uring_params::wq_fd to another io_uring fd with which you want to share backends._
> 
> Above commet is quoted from you in issue#324. And it is also for the same thread group, right?

Yes, it's exactly the same thing.

**Comment by korant96** [comment]
Thanks a lot~
I will closed the issue.
