### ISSUE TITLE
Be confused by IORING_FEAT_FAST_POLL and IORING_SETUP_IOPOLL

### ISSUE THREAD

**Issue by glenn-wang** [axboe/liburing#750]
After seeing some docs，I am confused by IORING_FEAT_FAST_POLL and IORING_SETUP_IOPOLL.

On NET IO，the two feature has what difference ？

Could give some explainations ？

**Comment by axboe** [comment]
There is no relation between the two. FAST_POLL tells you that the kernel will use an internal poll for readiness information, rather than punt to a worker thread. This is an efficiency optimization, makes working on those kinds of files much faster.

IOPOLL is polling for IO completion. It's only applicable to storage.

Both are described in the liburing man pages.

**Comment by axboe** [comment]
SQPOLL is more use case specific than networking. It allows you to offload submission to a thread, which means that an application can do IO without doing any system calls. But depending on the use case, this may or may not be a win.

FEAT_FAST_POLL has been available for a long time. Unless you're on a really ancient kernel, it'll be available.

PROVIDE_BUFFERS is indeed useful for networking to avoid allocating buffers for any request that is in flight. There's a newer variant of that, ring provided buffers, which is more efficient. See the io_uring_register_buf_ring(3) man page. This is only available on newer kernels.

Newer kernels in general provide a lot of nice wins for networking, particularly of interest are the IORING_SETUP_COOP_TASKRUN and IORING_SETUP_DEFER_TASKRUN setup flags. We've had some great results with the latter at Meta for networking workloads, in conjunction with the ring provided buffers mentioned above. But the DEFER_TASKRUN flag isn't available until 6.1, and COOP_TASKRUN and ring provided buffers are available in 6.0 and 5.19 respectively.
