### ISSUE TITLE
Not conformant to ISO C++

### ISSUE THREAD

**Issue by aaron-michaux** [axboe/liburing#755]
When building with `-Werror=pedantic` (as say, from unifex, or any other project), gcc complains that ISO C++ prohibits anonymous structs. As for example in the file `liburing/io_uring.h`

```
struct io_uring_sqe {
	__u8	opcode;		/* type of operation for this sqe */
	__u8	flags;		/* IOSQE_ flags */
	__u16	ioprio;		/* ioprio for the request */
	__s32	fd;		/* file descriptor to do IO on */
	union {
		__u64	off;	/* offset into file */
		__u64	addr2;
		struct {
			__u32	cmd_op;
			__u32	__pad1;
		};
	};
```

**Comment by DylanZA** [comment]
even in C -Werror=pedantic would fail due to 0 length arrays.

We could use pragmas (something like this https://github.com/DylanZA/liburing/commit/8cf66dcb19761f9e41be641cbd8caa5c2e7b73ba ), but I don't know if it is portable or even desired

**Comment by dormando** [comment]
I hate to "me too" but this does in fact also trigger in C under -Werror=pedantic

```
liburing/src/include/liburing/io_uring.h:96:25: warning: ISO C forbids zero-size array ‘cmd’ [-Wpedantic]
   96 |                 __u8    cmd[0];
      |                         ^~~
liburing/src/include/liburing/io_uring.h:630:41: warning: ISO C forbids zero-size array ‘bufs’ [-Wpedantic]
  630 |                 struct io_uring_buf     bufs[0];
      |                                         ^~~~
```

Is this intentional? Not sure why it's setting strict ISO C and then doing this.

**Comment by ammarfaizi2** [comment]
> Is this intentional?

Yes, it's intentional for readability purposes.

I once proposed a patch to change `bufs[0]` to `bufs[1]` to make it
work with pedantic but rejected.

See the reason here:
https://lore.kernel.org/io-uring/928d9094-db54-7b27-98a6-9ece514f12e1@kernel.dk

Also, that header comes from the Linux kernel tree. So, sadly, we
can't blame the Linux kernel for using the GNU extension. It's already
been like that since the beginning.

If we care about the C/C++ standard, specifically for portability, it
won't apply to liburing because liburing only works on Linux. So it
totally makes sense to use the GNU extension here.

> Not sure why it's setting strict ISO C and then doing this.

What does "it's" refer to here? I don't think liburing is built with
the pedantic flag.

**Comment by dormando** [comment]
Thanks, I understand this situation more. I use this pattern all over my own code and have no problem with it, I just have various flags set so my pedantic still passes.

It's a library so it's bound to run into people like me :)

**Comment by axboe** [comment]
Closing this one as we are bound by the kernel here in terms of zero sized or flexible arrays.

**Comment by bsbernd** [comment]
Hmm, I had actually thought that 0-length arrays are deprecated in the kernel as well - there were uapi patches to remove it? Like 

commit 94dfc73e7cf4a31da66b8843f0b9283ddd6b8381
Author: Gustavo A. R. Silva <gustavoars@kernel.org>
Date:   Wed Apr 6 19:36:51 2022 -0500

    treewide: uapi: Replace zero-length arrays with flexible-array members
    
And then there is https://people.kernel.org/kees/bounded-flexible-arrays-in-c
which points to DECLARE_FLEX_ARRAY

**Comment by alviroiskandar** [comment]
There is a pending patch from @kees for io_uring uapi change
https://lore.kernel.org/io-uring/20230105190507.gonna.131-kees@kernel.org
what do you think @axboe ?

Cc: @GustavoARSilva

**Comment by axboe** [comment]
Even if the arrays would be changed, we still have a bunch of things that will complain. So no, I don't think this is worth pursuing.

**Comment by ammarfaizi2** [comment]
> There is a pending patch from @kees for io_uring uapi change
> https://lore.kernel.org/io-uring/20230105190507.gonna.131-kees@kernel.org

Even with that change, it is still using the GNU extension. So it
doesn't make any difference. It's even using more GNU extensions than
it currently is. That patch doesn't fix the `-pedantic-errors` build.

With that patch applied, the error is worse:
```
ammarfaizi2@integral2:~/app/liburing$ clang -pedantic-errors zxc.c -o zxc.o
In file included from zxc.c:2:
./src/include/liburing/io_uring.h:96:12: error: zero size arrays are an extension [-Werror,-Wzero-length-array]
                __u8    cmd[0];
                            ^
./src/include/liburing/io_uring.h:630:3: error: empty struct is a GNU extension [-Werror,-Wgnu-empty-struct]
                __DECLARE_FLEX_ARRAY(struct io_uring_buf, bufs);
                ^
/usr/include/linux/stddef.h:44:3: note: expanded from macro '__DECLARE_FLEX_ARRAY'
                struct { } __empty_ ## NAME; \
                ^
In file included from zxc.c:2:
./src/include/liburing/io_uring.h:619:2: error: '' may not be nested in a struct due to flexible array member [-Werror,-Wflexible-array-extensions]
        union {
        ^
3 errors generated.
```

**Comment by axboe** [comment]
Yes, so let's please just put this one to rest. There's a reason why I don't enable any kind of pedantic errors on sw I maintain - it causes a LOT more issues than it solves. A new compiler will generate different pedantic warnings, and now it fails to compile for someone who downloaded it rather than not spew warnings or perhaps still work but with warnings.

So no, it's not happening, and I don't want to hear about it again.
