### ISSUE TITLE
"Arbitrary" limit on fixed buffer size

### ISSUE THREAD

**Issue by brandon-feder** [axboe/liburing#768]
It seams that io_uring imposes an "arbitrary" maximum size pf 1G on fixed buffers: https://patchwork.kernel.org/project/linux-block/patch/20190201152414.23296-13-axboe@kernel.dk/. I have several files many terabytes in size. I would like to asynchronously read and write between these files and a buffer in RAM in several gigabyte large "chunks".

1. What is the motivation behind this limit? Is there a safe way I can remove this limit?
2. Is there a fast alternative to using the fixed buffers?
3. Is io_uring even the right tool for this job?

Thanks!

**Comment by axboe** [comment]
There's no real motivation behind the limit, other than "we needed a limit of some sorts". Note that Linux does NOT allow more than INT_MAX in a single data transfer, so logically I guess we should make it 2GB in size. Since you can have many registered buffers, I suspect this would suffice for you? In any case, there's not going to be a win between doing 1GB vs 2GB transfers, everything else is in the noise at that point. So in practice, while the limit is 1G, I don't see this making much of a difference. Devices also don't support transfers that large, anything larger than their max command size would be split into multiples anyway. I strongly suspect you'll be better off using eg 1MB ios even if you have many large 1GB buffers registered. You can index and use them for concurrent ios without issue.

3. Yes of course ;-)

**Comment by brandon-feder** [comment]
Okay. I will try this. I appreciate your help. Thanks!
