### ISSUE TITLE
'io_uring_enable_rings' not exposed

### ISSUE THREAD

**Issue by jmccl** [axboe/liburing#773]
As 'io_uring_enable_rings' is not in 'liburing.map' it is not marked as an external symbol in 'liburing.so'. This results in package managers (arch and debian at least) build systems stripping the symbol from the shared object when striping symbols. The upshot is that the function can be referenced by user code at compile time as it's in the header, but linking to the shared object fails due to an undefined reference to the function. 

https://github.com/axboe/liburing/blob/master/src/liburing.map

(liburing.map is a 'version-script' parameter to the linker when linking liburing.so.)

Is this a bug, or is the intent to not publicly expose this function?

(The initial issue is here, fwiw: https://github.com/facebook/proxygen/issues/434)

**Comment by axboe** [comment]
That's just an oversight... Want to send in a patch?

**Comment by jmccl** [comment]
Sure, but before I do, here's a list of symbols that are in a non-stripped library that are also not external.

`
$ nm pkg/liburing/usr/lib/liburing.so | grep " t "
0000000000002720 t deregister_tm_clones
0000000000002790 t __do_global_dtors_aux
0000000000003980 t _fini
00000000000027e0 t frame_dummy
0000000000002000 t _init
0000000000003680 t io_uring_enable_rings
0000000000002c70 t __io_uring_flush_sq
00000000000027f0 t _io_uring_get_cqe
0000000000003650 t io_uring_register_restrictions
0000000000002a40 t __io_uring_submit
0000000000002d50 t __io_uring_submit_timeout
0000000000002750 t register_tm_clones
`

Should any of those also be in the patch?

**Comment by ammarfaizi2** [comment]
- `io_uring_enable_rings` should be exported.

- `__io_uring_flush_sq` is marked as static since commit 7fc973fc6626
  ("queue: Mark __io_uring_flush_sq() as static"). This function was
  never exported despite it was not marked as `static` in <= 2.3. This
  function should NOT be exported.

- `_io_uring_get_cqe` is a static function.

- `io_uring_register_restrictions` should be exported.

- `__io_uring_submit` is a static function.

- `__io_uring_submit_timeout` is a static function.

Static functions should NOT be exported.
