### ISSUE TITLE
Timeout for `io_uring_peek_batch_cqe`

### ISSUE THREAD

**Issue by YoSTEALTH** [axboe/liburing#89]
Could **timeout** feature be added to `io_uring_peek_batch_cqe` with `ts` as its parameter?

`io_uring_peek_batch_cqe(struct io_uring *ring, struct io_uring_cqe **cqes, unsigned count);`

`io_uring_peek_batch_cqe(struct io_uring *ring, struct io_uring_cqe **cqes, unsigned count, struct __kernel_timespec *ts);`

Thank You

**Comment by axboe** [comment]
Any _peek() variant just peeks at the ring, and returns events that are already available. It'll never wait, and hence it doesn't make sense to attach a timeout to it. The function will always return immediately, whether or not there are events available or not.

**Comment by YoSTEALTH** [comment]
As long as there is sqe/cqe being process there is no problem. If you have a server running and there is 0 traffic, now this process goes into nonestop lookup at 100% load. Thus some kind of wait/sleep is required even for a millisecond.

Getting a count of ready events is important, this i can't do using `io_uring_wait_cqes`, ...

```
wait = 2
received = io_uring_peek_batch_cqe(ring, cqes, wait)
if received:
    for i in range(received):
        cqe = cqes[i]
        # do something with each `cqe` ready
else:
    time.sleep(0.0005)  # blocking, probably not the best solution?!`

**Comment by axboe** [comment]
That's because you're busy looping at that point, keep peeking and there's nothing there. Why don't you just use io_uring_wait_cqe() at that point? Not quite sure I understand what you're trying to accomplish. If you have no sqe in-flight, you shouldn't call either of them. If you have one or more, and you peek and get one, you can complete it. If none are available and you have one in-flight, you should not use a random sleep interval, you should use io_uring_wait_cqe(), or some variant thereof.

**Comment by YoSTEALTH** [comment]
First of all thank you for your immense amount of patience and helpfulness, really do appreciate it.

In case of server `io_uring_prep_poll_add(sqe, socket_fd, POLLIN)` would be in waiting state. Thus there is something to peek to see if it was activated.

Switch between using `io_uring_peek_cqe` and `io_uring_wait_cqe` hmm... I will have to try it out.

Tomorrow though, crashing for now...

Thanks again, good night :)

**Comment by YoSTEALTH** [comment]
Looks like switching to `io_uring_wait_cqe` vs timeout/sleep does the trick :)
