### ISSUE TITLE
io_uring_prep_socket_direct -> bind -> listen -> io_uring_prep_accept_direct

### ISSUE THREAD

**Issue by ghost** [axboe/liburing#941]
https://github.com/axboe/liburing/issues/234#issuecomment-1241888695
why are bind and listen not async yet,
can they access direct descriptor?

**Comment by isilence** [comment]
> why are bind and listen not async yet

Because they don't need to be async as they don't wait on any IO / etc. If the question why they're not supported by io_uring, then there wasn't much need before / because nobody implemented it.

> can they access direct descriptor?

Direct descriptiors is an io_uring feature, so no

> does this mean that tcp servers using io_uring now need to handle both direct and global file descriptors?

as a work around you can register a socket file after doing bind/listen, see `io_uring_register_files()`
